### ISSUE TITLE
not able to search guild store after new update

### ISSUE THREAD

**Issue by bortsmithson** [mcdonnelldean/eso-pad-merchant#9]
With the horns of the reach update I keep getting this error when trying to search guild stores.  Not really sure if its padmerchant but figured you might know more about it than I do.
![20170820115921_1](https://user-images.githubusercontent.com/31189890/29497430-a35596a8-85a4-11e7-8b19-85beb9b2d1f4.jpg)

**Comment by mcdonnelldean** [comment]
Noted. This is due to a code change in MM. This change is pretty fundamental and may cause the addon to be abandoned. I've left a comment on the MM comment section asking for an official way to integrate, lets see how that progresses. http://www.esoui.com/downloads/fileinfo.php?id=928&so=DESC#comments

**Comment by mcdonnelldean** [comment]
Fixed in next version.
